import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import code from "../../public/images/svgs/miscellaneous_icons_2.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mittow | Main Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">

            {/* IMAGEN PRINCIPAL */}
            <div className="w-1/2">
              <Image src={profilePic} alt="Franco" className="w-full h-auto" 
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>

            {/* TITULO DEL TEXTO */}
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Full Stack Web Developer (MERN)"
                className="!text-6xl !text-left"
              />

              {/* TEXTO */}
              <p className="my-4 text-base font-medium">
                Como desarrollador full-stack, me dedico a convertir ideas en
                aplicaciones web innovadoras. Explore mis últimos proyectos
                donde muestro mi experiencia en el desarrollo web con
                javascript.
              </p>

              {/* BOTONES DE CV Y CONTACT */}
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/CV_(SPANISH).pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg 
                  text-lg font-semibold hover:bg-light hover:text-dark border-2 
                  border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark
                  hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                  download={true}
                >
                  Curriculum <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:franco3007199@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        {/* BTN ANIMADO */}
        <HireMe />
        <div className="absolute right-32 -bottom-6 inline-block w-40">
          <Image src={code} alt="Code" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
