import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-5.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import code from "../../public/images/svgs/miscellaneous_icons_2.svg";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dev | Main Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex min-h-screen items-center text-dark dark:text-light sm:items-start">
        <Layout className="!pt-0 md:!pt-16 sm:!pt-16">
          <div className="flex items-center justify-between w-full md:flex-col">
            {/* IMAGEN PRINCIPAL */}
            <div className="w-1/2 lg:hidden md:inline-block md:w-full">
              <Image
                src={profilePic}
                alt="Imagen de Franco"
                className="w-full h-auto"
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>

            {/* TITULO DEL TEXTO */}
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Software Developer"
                className="!text-5xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl
                md:!text-5xl sm:!text-3xl"
              />

              {/* TEXTO */}
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Soy un profesional apasionado por el mundo de la informática,
                con experiencia en despligue de aplicaciones, testeando y
                desarrollando software. Soy una persona responsable, adaptable y
                comprometido con mi trabajo.
              </p>

              {/* BOTONES DE CV Y CONTACT */}
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Gian_Bianco.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg 
                  text-lg font-semibold hover:bg-light hover:text-dark border-2 
                  border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark
                  hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                  md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Currículum <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:franco3007199@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light
                  md:text-base"
                >
                  Contáctame
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        {/* BTN ANIMADO */}
        <HireMe />

        {/* SVG (COMPUTER) */}
        <div className="absolute right-8 bottom-8 inline-block w-40 lg:hidden">
          <Image src={code} alt="Code" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
